### ISSUE TITLE
dotnet test works, but not dotnet run

### ISSUE THREAD

**Issue by simkimsia** [EventStore/training-dotnet-daytwothree#14]
I followed the readme

i got this for dotnet run

![CleanShot 2022-04-30 at 09 49 16](https://user-images.githubusercontent.com/245021/166085913-8155cc9a-a2d1-42cc-9f68-695d9c60a4f0.png)

**Comment by ylorph** [comment]
assuming you're at the root of the repo
`docker-compose up -d`  or `docker-compose -f docker-compose.arm64.yml` up on a M1 
then 
`dotnet run --project ./Scheduling/Scheduling.csproj`

**Comment by simkimsia** [comment]
@ylorph  thank you

I saw this 
![image](https://user-images.githubusercontent.com/245021/166418762-2a9b4d0a-9cf0-43f6-9917-b44d6b015537.png)


Is that the visible sign that I expect to see? Do i need to run some webpage pointing to some localhost url?

**Comment by ylorph** [comment]
no that's good enough to know it runs
